"""SAMTok adaptation built on DiffSynth's official training runners.

The DiffSynth runner owns DDP, optimizer, accumulation, logging, checkpointing,
and the two split-training tasks.  This module supplies the SAMTok-specific
model forward, metadata schedule, and cache manifest around those interfaces.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import torch
from accelerate import Accelerator, DistributedDataParallelKwargs
from accelerate.utils import DataLoaderConfiguration
from torch.utils.data import Dataset, SequentialSampler

DIFFSYNTH_ROOT = Path(__file__).resolve().parents[1] / "DiffSynth-Studio"
if str(DIFFSYNTH_ROOT) not in sys.path:
    sys.path.insert(0, str(DIFFSYNTH_ROOT))

from diffsynth.diffusion.logger import ModelLogger  # noqa: E402
from diffsynth.diffusion.runner import (  # noqa: E402
    launch_data_process_task,
    launch_training_task,
)
from diffsynth.diffusion.training_module import DiffusionTrainingModule  # noqa: E402

from .data import (  # noqa: E402
    file_hash,
    load_images,
    make_schedule,
    read_rows,
    row_hash,
    write_json,
)
from .model import DEFAULT_QWEN, DEFAULT_SAMTOK  # noqa: E402
from .training import (  # noqa: E402
    adapter_identity,
    add_adapter,
    flow_loss,
    load_adapter,
    prepare_fm,
    resize_sources,
    save_adapter,
    validate_conditioning,
)
from .model import load_pipeline, ntp_loss  # noqa: E402


def _cpu(value: Any):
    if isinstance(value, torch.Tensor):
        return value.detach().cpu()
    if isinstance(value, list):
        return [_cpu(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_cpu(item) for item in value)
    if isinstance(value, dict):
        return {key: _cpu(item) for key, item in value.items()}
    return value


class ScheduledMetadata(Dataset):
    """Metadata dataset with a global, rank-aware schedule.

    DiffSynth's runner normally asks DataLoader to shuffle.  Exposing an
    schedule_sampler lets the runner retain all of its optimizer/DDP logic
    while consuming the exact schedule generated by ``make_schedule``.
    """

    load_from_cache = False

    def __init__(self, rows, schedule):
        self.rows = rows
        self.schedule = list(schedule)
        self.schedule_sampler = SequentialSampler(self)

    def __len__(self):
        return len(self.schedule)

    def __getitem__(self, index):
        return dict(self.rows[self.schedule[index]])


class ScheduledCache(Dataset):
    """Cache dataset that uses the same schedule as metadata training."""

    load_from_cache = True

    def __init__(self, rows, cache_dir, schedule):
        self.rows = rows
        self.cache_dir = Path(cache_dir)
        self.schedule = list(schedule)
        self.schedule_sampler = SequentialSampler(self)

    def __len__(self):
        return len(self.schedule)

    def __getitem__(self, index):
        row = self.rows[self.schedule[index]]
        path = self.cache_dir / row["_cache_file"]
        return torch.load(path, map_location="cpu", weights_only=True)


def verify_cache(cache_dir, manifest):
    """Validate DiffSynth runner shards before Stage 2 consumes them."""
    cache_dir = Path(cache_dir)
    if manifest.get("format") != "samtok21-cache-v1":
        raise ValueError("Unexpected cache format")
    rows = manifest.get("rows", [])
    if not rows:
        raise ValueError("Cache manifest is empty")
    for row in rows:
        relative = row.get("_cache_file")
        if not relative or Path(relative).is_absolute():
            raise ValueError("Cache file must be a relative path")
        path = cache_dir / relative
        side_path = path.with_suffix(".json")
        if not path.is_file() or not side_path.is_file():
            raise ValueError(f"Missing cache shard or sidecar: {relative}")
        side = json.loads(side_path.read_text())
        original = {key: value for key, value in row.items() if key != "_cache_file"}
        if side.get("row_hash") != row_hash(original):
            raise ValueError(f"Cache row hash mismatch: {relative}")
        if side.get("sha256") != file_hash(path):
            raise ValueError(f"Cache checksum mismatch: {relative}")
        validate_conditioning(torch.load(path, map_location="cpu", weights_only=True))
    return True


class SamtokTrainingModule(DiffusionTrainingModule):
    """DiffSynth runner adapter for Stage 1, cache, and Stage 2."""

    def __init__(self, args, task: str):
        super().__init__()
        self.args = args
        self.task = task
        self.stage = args.stage
        if task == "sft:data_process":
            components = ("text_encoder", "vae")
        elif args.stage == "stage2":
            components = ("dit",)
        else:
            components = ("text_encoder", "dit", "vae")
        self.pipe = load_pipeline(
            args.qwen, args.samtok, device=args.device, components=components
        )
        self.pipe.scheduler.set_timesteps(1000, training=True)

        if task == "sft:data_process":
            if not args.te_adapter:
                raise ValueError("cache requires --te-adapter")
            load_adapter(self.pipe.text_encoder, args.te_adapter, trainable=False)
        elif args.init_adapter:
            target = self.pipe.text_encoder if args.stage == "stage1" else self.pipe.dit
            loaded = load_adapter(target, args.init_adapter, trainable=True)
            if loaded["stage"] != args.stage:
                raise ValueError("--init-adapter belongs to a different stage")
        else:
            target = self.pipe.text_encoder if args.stage == "stage1" else self.pipe.dit
            add_adapter(target, args.stage, args.rank, args.dropout)

        if args.stage == "stage1":
            self.pipe.text_encoder.model.gradient_checkpointing_enable(
                gradient_checkpointing_kwargs={"use_reentrant": False}
            )
            self.pipe.text_encoder.train()
            self.pipe.text_encoder.model.model.visual.eval()
        elif task == "sft:train":
            self.pipe.dit.train()
        else:
            self.pipe.eval()

    def forward(self, data, inputs=None):
        if self.task == "sft:data_process":
            prepared = prepare_fm(
                self.pipe, data, self.args.base_path, self.args.max_pixels, te_grad=False
            )
            validate_conditioning(prepared)
            return _cpu(prepared)

        if self.stage == "stage2":
            if inputs is None:
                raise ValueError("Stage 2 training expects cached inputs")
            validate_conditioning(inputs)
            loss, metrics = flow_loss(self.pipe, inputs)
        elif data["sample_type"] == "edit_ntp":
            images, _, height, width = load_images(
                data, self.args.base_path, self.args.max_pixels
            )
            images = resize_sources(self.pipe, images, height, width)
            loss, metrics = ntp_loss(self.pipe, data["prompt"], images, data["mt_cot"])
            loss = loss * self.args.ntp_weight
        else:
            prepared = prepare_fm(
                self.pipe, data, self.args.base_path, self.args.max_pixels, te_grad=True
            )
            loss, metrics = flow_loss(self.pipe, prepared)
            loss = loss * self.args.fm_weight
        self.last_metrics = metrics
        return loss

    def after_backward_audit(self):
        trainable = [p for p in self.parameters() if p.requires_grad]
        frozen_with_grad = sum(
            p.grad is not None for p in self.parameters() if not p.requires_grad
        )
        norms = [p.grad.detach().float().norm() for p in trainable if p.grad is not None]
        total = float(torch.stack(norms).norm().item()) if norms else 0.0
        if not torch.isfinite(torch.tensor(total)) or frozen_with_grad:
            raise RuntimeError(
                f"Invalid gradient audit: total={total}, "
                f"frozen_with_grad={frozen_with_grad}"
            )
        return {
            "grad_norm_before_clip": total,
            "trainable_grad_tensors": len(norms),
            "nonzero_grad_tensors": sum(float(n) > 0 for n in norms),
            "frozen_grad_tensors": frozen_with_grad,
        }


def _accelerator(accumulation=1):
    return Accelerator(
        gradient_accumulation_steps=accumulation,
        kwargs_handlers=[DistributedDataParallelKwargs(find_unused_parameters=False)],
        dataloader_config=DataLoaderConfiguration(even_batches=False),
    )


def _schedule_dataset(args, accelerator, rows):
    block_len = 8 if args.stage == "stage1" else 4
    if accelerator.num_processes > 1 and args.accumulation % block_len:
        raise ValueError(
            f"For per-rank exact {args.stage} ratios, accumulation must be a multiple "
            f"of {block_len}; got {args.accumulation}"
        )
    schedule, report = make_schedule(
        rows,
        args.stage,
        accelerator.num_processes,
        args.accumulation,
        steps=args.steps,
        seed=args.seed,
    )
    return schedule, report


def run_train(args):
    accelerator = _accelerator(args.accumulation)
    # Transformers' ``device_map={"": "cuda"}`` resolves to CUDA device 0.
    # Bind every rank explicitly before loading Qwen3 and DiffSynth modules so
    # each process owns only its local GPU.
    args.device = str(accelerator.device)
    if args.stage == "stage2":
        manifest = json.loads((Path(args.cache) / "manifest.json").read_text())
        verify_cache(args.cache, manifest)
        rows = manifest["rows"]
        for row in rows:
            row["_cache_file"] = row["_cache_file"]
        schedule, report = _schedule_dataset(args, accelerator, rows)
        dataset = ScheduledCache(rows, args.cache, schedule)
    else:
        rows = read_rows(args.metadata)
        schedule, report = _schedule_dataset(args, accelerator, rows)
        dataset = ScheduledMetadata(rows, schedule)

    model = SamtokTrainingModule(args, "sft:train")
    logger = ModelLogger(
        args.output,
        remove_prefix_in_ckpt="pipe.text_encoder."
        if args.stage == "stage1"
        else "pipe.dit.",
        enable_csv_log=True,
    )
    if accelerator.is_main_process:
        Path(args.output).mkdir(parents=True, exist_ok=True)
        write_json(Path(args.output) / "schedule.json", report)
    launch_training_task(
        accelerator,
        dataset,
        model,
        logger,
        learning_rate=args.lr,
        weight_decay=args.weight_decay,
        num_workers=args.num_workers,
        save_steps=args.save_steps,
        num_epochs=1,
        max_grad_norm=args.max_grad_norm,
        args=None,
    )
    # ModelLogger keeps the DiffSynth step checkpoint format.  Also emit the
    # compact adapter directory consumed by Stage 1 cache construction and by
    # --init-adapter, so the two training tasks compose without conversion.
    accelerator.wait_for_everyone()
    if accelerator.is_main_process:
        adapter_config = {
            "stage": args.stage,
            "rank": args.rank,
            "dropout": args.dropout,
        }
        if args.stage == "stage2":
            adapter_config["conditioning_identity"] = manifest["identity"]
        save_adapter(
            accelerator.unwrap_model(model).pipe.text_encoder
            if args.stage == "stage1"
            else accelerator.unwrap_model(model).pipe.dit,
            Path(args.output) / "adapter",
            adapter_config,
        )


def _cache_manifest(args, accelerator, rows):
    if not accelerator.is_main_process:
        return
    output = Path(args.output)
    entries = []
    for rank_dir in sorted(p for p in output.iterdir() if p.is_dir() and p.name.isdigit()):
        rank = int(rank_dir.name)
        files = sorted(rank_dir.glob("*.pth"), key=lambda p: int(p.stem))
        for local_id, path in enumerate(files):
            row_index = rank + local_id * accelerator.num_processes
            if row_index >= len(rows):
                raise ValueError("Cache shard has more files than metadata rows")
            row = rows[row_index]
            side = {
                "row_index": row_index,
                "row_hash": row_hash(row),
                "sha256": file_hash(path),
                "qwen": args.qwen,
                "samtok": args.samtok,
                "te_adapter": args.te_adapter,
                "te_adapter_identity": adapter_identity(args.te_adapter),
                "max_pixels": args.max_pixels,
            }
            write_json(path.with_suffix(".json"), side)
            entries.append({**row, "_cache_file": str(path.relative_to(output))})
    write_json(
        output / "manifest.json",
        {
            "format": "samtok21-cache-v1",
            "identity": {
                "metadata_sha256": file_hash(args.metadata),
                "qwen": args.qwen,
                "samtok": args.samtok,
                "te_adapter": args.te_adapter,
                "te_adapter_identity": adapter_identity(args.te_adapter),
                "max_pixels": args.max_pixels,
            },
            "rows": entries,
        },
    )


def run_cache(args):
    accelerator = _accelerator()
    args.device = str(accelerator.device)
    rows = read_rows(args.metadata)
    dataset = ScheduledMetadata(rows, list(range(len(rows))))
    model = SamtokTrainingModule(args, "sft:data_process")
    logger = ModelLogger(args.output)
    launch_data_process_task(
        accelerator, dataset, model, logger, num_workers=args.num_workers, args=None
    )
    accelerator.wait_for_everyone()
    _cache_manifest(args, accelerator, rows)


def _parser():
    parser = argparse.ArgumentParser(description="SAMTok with DiffSynth runners")
    sub = parser.add_subparsers(dest="command", required=True)
    for command in ("cache", "train"):
        p = sub.add_parser(command)
        p.add_argument("--qwen", default=DEFAULT_QWEN)
        p.add_argument("--samtok", default=DEFAULT_SAMTOK)
        p.add_argument("--output", required=True)
        p.add_argument("--base-path", default=".")
        p.add_argument("--max-pixels", type=int, default=1048576)
        p.add_argument("--num-workers", type=int, default=0)
        p.add_argument("--device", default="cuda")
        p.add_argument("--metadata")
        p.add_argument("--cache")
        p.add_argument("--te-adapter")
        p.add_argument("--stage", choices=("stage1", "stage2"), default="stage2")
        p.add_argument("--steps", type=int)
        p.add_argument("--accumulation", type=int)
        p.add_argument("--rank", type=int)
        p.add_argument("--dropout", type=float)
        p.add_argument("--lr", type=float)
        p.add_argument("--weight-decay", type=float)
        p.add_argument("--ntp-weight", type=float, default=0.05)
        p.add_argument("--fm-weight", type=float, default=1.0)
        p.add_argument("--max-grad-norm", type=float, default=1.0)
        p.add_argument("--seed", type=int, default=20260920)
        p.add_argument("--save-steps", type=int, default=100)
        p.add_argument("--init-adapter")
    return parser


def main():
    args = _parser().parse_args()
    defaults = {
        "stage1": {"accumulation": 8, "rank": 64, "dropout": 0.05, "lr": 4e-5, "weight_decay": 0.05},
        "stage2": {"accumulation": 4, "rank": 32, "dropout": 0.0, "lr": 1e-4, "weight_decay": 0.01},
    }[args.stage]
    for key, value in defaults.items():
        if getattr(args, key) is None:
            setattr(args, key, value)
    if args.command == "cache":
        if not args.metadata or not args.te_adapter:
            raise SystemExit("cache requires --metadata and --te-adapter")
        run_cache(args)
    else:
        if args.stage == "stage1" and not args.metadata:
            raise SystemExit("stage1 train requires --metadata")
        if args.stage == "stage2" and not args.cache:
            raise SystemExit("stage2 train requires --cache")
        run_train(args)


if __name__ == "__main__":
    main()
