"""SAMTok adaptation built on DiffSynth's official training runners.

The DiffSynth runner owns DDP, optimizer, accumulation, logging, checkpointing,
and the two split-training tasks.  This module supplies the SAMTok-specific
model forward, metadata schedule, and cache manifest around those interfaces.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import torch
from accelerate import Accelerator, DistributedDataParallelKwargs
from accelerate.utils import DataLoaderConfiguration, InitProcessGroupKwargs, broadcast_object_list, gather_object, set_seed
from torch.utils.data import Dataset, SequentialSampler

from diffsynth.diffusion.logger import ModelLogger  # noqa: E402
from diffsynth.diffusion.runner import (  # noqa: E402
    launch_data_process_task,
    launch_training_task,
)
from diffsynth.diffusion.training_module import DiffusionTrainingModule  # noqa: E402

from samtok_edit21.data.io import (  # noqa: E402
    file_hash,
    load_images,
    make_schedule,
    read_rows,
    row_hash,
    row_kind,
    write_json,
)
from samtok_edit21.models.pipeline import DEFAULT_QWEN, DEFAULT_SAMTOK  # noqa: E402
from samtok_edit21.training.objectives import (  # noqa: E402
    adapter_identity,
    add_adapter,
    flow_loss,
    load_adapter,
    prepare_fm,
    resize_sources,
    save_adapter,
    validate_conditioning,
)
from samtok_edit21.models.pipeline import load_pipeline, ntp_loss  # noqa: E402
from samtok_edit21.data.provenance import (
    FORMAT,
    assert_models_match,
    conditioning_identity,
    validate_cache_manifest,
    verify_cache,  # re-exported for existing callers/tests
    verify_cache_shard,
)



def _cpu(value: Any):
    if isinstance(value, torch.Tensor):
        return value.detach().cpu()
    if isinstance(value, list):
        return [_cpu(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_cpu(item) for item in value)
    if isinstance(value, dict):
        return {key: _cpu(item) for key, item in value.items()}
    return value


class ScheduledMetadata(Dataset):
    """Metadata dataset with a global, rank-aware schedule.

    DiffSynth's runner normally asks DataLoader to shuffle.  Exposing an
    schedule_sampler lets the runner retain all of its optimizer/DDP logic
    while consuming the exact schedule generated by ``make_schedule``.
    """

    load_from_cache = False

    def __init__(self, rows, schedule, *, cache=False):
        self.rows = rows
        self.cache = cache
        self.schedule = list(schedule)
        self.schedule_sampler = SequentialSampler(self)

    def __len__(self):
        return len(self.schedule)

    def __getitem__(self, index):
        row_index = self.schedule[index]
        row = dict(self.rows[row_index])
        if self.cache:
            row['_row_index'] = row_index
        return row


class ScheduledCache(Dataset):
    """Cache dataset that uses the same schedule as metadata training."""

    load_from_cache = True

    def __init__(self, rows, cache_dir, schedule):
        self.rows = rows
        self.cache_dir = Path(cache_dir)
        self.schedule = list(schedule)
        self.schedule_sampler = SequentialSampler(self)

    def __len__(self):
        return len(self.schedule)

    def __getitem__(self, index):
        row = self.rows[self.schedule[index]]
        path = self.cache_dir / row["_cache_file"]
        payload = torch.load(path, map_location="cpu", weights_only=True)
        inputs = payload["inputs"]
        inputs["_sample_kind"] = row_kind(row)
        inputs["_sample_row_sha256"] = payload["row_hash"]
        return inputs


class SamtokTrainingModule(DiffusionTrainingModule):
    """DiffSynth runner adapter for Stage 1, cache, and Stage 2."""

    def __init__(self, args, task: str):
        super().__init__()
        self.args = args
        self.task = task
        self.stage = args.stage
        self.completed_updates = 0
        self.pending_metrics = []
        self.region_store = None
        if getattr(args, "region_cache", None) and (args.stage == "stage1" or task == "sft:data_process"):
            from samtok_edit21.regions.supervision import RegionStore
            self.region_store = RegionStore(args.region_cache, args.max_pixels)
        if task == "sft:data_process":
            components = ("text_encoder", "vae")
        elif args.stage == "stage2":
            components = ("dit",)
        else:
            components = ("text_encoder", "dit", "vae")
        self.pipe = load_pipeline(
            args.qwen, args.samtok, device=args.device, components=components
        )
        self.pipe.scheduler.set_timesteps(1000, training=True)

        if task == "sft:data_process":
            if not args.te_adapter:
                raise ValueError("cache requires --te-adapter")
            load_adapter(self.pipe.text_encoder, args.te_adapter, trainable=False)
        elif args.init_adapter:
            target = self.pipe.text_encoder if args.stage == "stage1" else self.pipe.dit
            loaded = load_adapter(target, args.init_adapter, trainable=True)
            if loaded["stage"] != args.stage:
                raise ValueError("--init-adapter belongs to a different stage")
        else:
            target = self.pipe.text_encoder if args.stage == "stage1" else self.pipe.dit
            add_adapter(target, args.stage, args.rank, args.dropout)

        if task == "sft:data_process":
            self.pipe.eval()
        elif args.stage == "stage1":
            self.pipe.text_encoder.model.gradient_checkpointing_enable(
                gradient_checkpointing_kwargs={"use_reentrant": False}
            )
            self.pipe.text_encoder.train()
            self.pipe.text_encoder.model.model.visual.eval()
        elif task == "sft:train":
            self.pipe.dit.train()
        else:
            self.pipe.eval()
        if task == "sft:train":
            self._branch_grad_peaks = []
            for parameter in self.parameters():
                if parameter.requires_grad:
                    parameter.register_hook(self._observe_branch_gradient)

    def _observe_branch_gradient(self, gradient):
        # Hooks observe this backward, not gradients left by earlier accumulated
        # microsteps. Zero LoRA-A gradients at initialization remain valid.
        self._branch_grad_peaks.append(gradient.detach().abs().amax().float())

    def _supervision(self, row):
        return None if self.region_store is None else self.region_store.load(row, self.args.base_path)

    def _flow(self, inputs):
        base = self.args.attention_weight
        warmup = self.args.attention_warmup_steps
        effective = base * (min(self.completed_updates / warmup, 1.0) if warmup else 1.0)
        return flow_loss(self.pipe, inputs, stage=self.stage, region_weight=self.args.region_weight,
                         region_n_min=self.args.region_n_min, attention_weight=effective,
                         attention_layers=self.args.attention_layers if base else (),
                         attention_read_weight=self.args.attention_read_weight)

    def on_optimizer_step(self, completed_updates, accelerator, skipped=False, learning_rate=None):
        """One collective per accumulation window; logs are per-sample means."""
        self.completed_updates = completed_updates
        records = gather_object(self.pending_metrics)
        # In single-process mode gather_object returns the SAME list.
        # Rebind rather than clear, otherwise the gathered records disappear.
        self.pending_metrics = []
        if accelerator.is_main_process:
            from collections import Counter, defaultdict
            values = defaultdict(list)
            for record in records:
                for key, value in record.items():
                    if isinstance(value, (float, int)) and not key.startswith("_"):
                        values[key].append(value)
            entry = {"optimizer_step": completed_updates, "skipped": skipped,
                     "samples": len(records), "world_size": accelerator.num_processes,
                     "branches": dict(Counter(r["_branch"] for r in records)),
                     "rank_samples": dict(Counter(str(r["_rank"]) for r in records)),
                     "metrics": {k: sum(v) / len(v) for k, v in values.items()},
                     "counts": {k: len(v) for k, v in values.items()},
                     "gradient_zero_reasons": dict(Counter(r["_gradient_zero_reason"] for r in records if "_gradient_zero_reason" in r)),
                     "skip_reasons": dict(Counter(r["region_skip_reason"] for r in records if "region_skip_reason" in r))}
            with (Path(self.args.output) / "training_metrics.jsonl").open("a") as stream:
                stream.write(json.dumps(entry) + "\n")
            if self.args.region_weight or self.args.attention_weight:
                with (Path(self.args.output) / "supervision_metrics.jsonl").open("a") as stream:
                    stream.write(json.dumps(entry) + "\n")
        else:
            entry = None
        if hasattr(self, "tracker"):
            self.tracker.log(entry, learning_rate)

    def forward(self, data, inputs=None):
        self._branch_grad_peaks = []
        if self.task == "sft:data_process":
            prepared = prepare_fm(
                self.pipe, data, self.args.base_path, self.args.max_pixels, te_grad=False,
                supervision=self._supervision(data)
            )
            validate_conditioning(prepared)
            original = {k: v for k, v in data.items() if k != "_row_index"}
            return {"inputs": _cpu(prepared), "row_index": data["_row_index"],
                    "row_hash": row_hash(original), "identity": self.args.conditioning_identity}

        if self.stage == "stage2":
            if inputs is None:
                raise ValueError("Stage 2 training expects cached inputs")
            inputs = dict(inputs)
            cached_branch = inputs.pop("_sample_kind", "cached_fm")
            sample_hash = inputs.pop("_sample_row_sha256", None)
            validate_conditioning(inputs)
            loss, metrics = self._flow(inputs)
        elif data["sample_type"] == "edit_ntp":
            images, _, height, width = load_images(
                data, self.args.base_path, self.args.max_pixels
            )
            images = resize_sources(self.pipe, images, height, width)
            loss, metrics = ntp_loss(self.pipe, data["prompt"], images, data["mt_cot"])
            loss = loss * self.args.ntp_weight
        else:
            prepared = prepare_fm(
                self.pipe, data, self.args.base_path, self.args.max_pixels, te_grad=True,
                supervision=self._supervision(data)
            )
            if not prepared["prompt_embeds"].requires_grad:
                raise RuntimeError("FM lost its gradient connection to TE")
            loss, metrics = self._flow(prepared)
            loss = loss * self.args.fm_weight
        if not torch.isfinite(loss).all() or not loss.requires_grad:
            raise RuntimeError('Loss must be finite and differentiable')
        self.last_metrics = metrics
        branch = cached_branch if self.stage == "stage2" else row_kind(data)
        self.pending_metrics.append({**metrics, "weighted_total": loss.detach().item(),
                                     "_row_sha256": sample_hash if self.stage == "stage2" else row_hash(data),
                                     "_branch": branch, "_rank": int(os.environ.get("RANK", 0))})
        return loss

    def after_backward_audit(self):
        from samtok_edit21.training.gradient_audit import audit_backward
        return audit_backward(self)


def _accelerator(accumulation=1):
    return Accelerator(
        gradient_accumulation_steps=accumulation,
        kwargs_handlers=[DistributedDataParallelKwargs(find_unused_parameters=False),
                         InitProcessGroupKwargs(timeout=timedelta(seconds=int(
                             os.environ.get("SAMTOK_DISTRIBUTED_TIMEOUT_SECONDS", "1800"))))],
        dataloader_config=DataLoaderConfiguration(even_batches=False),
    )


def verify_rank_parameters(model, accelerator, output):
    """Verify that synchronized optimization left identical trainable weights."""
    import hashlib
    digest, count = hashlib.sha256(), 0
    for name, parameter in sorted(accelerator.unwrap_model(model).named_parameters()):
        if parameter.requires_grad:
            digest.update(name.encode())
            digest.update(parameter.detach().float().cpu().contiguous().numpy().tobytes())
            count += parameter.numel()
    records = gather_object([{"rank": accelerator.process_index, "sha256": digest.hexdigest(),
                              "trainable_parameters": count,
                              "peak_memory_gib": torch.cuda.max_memory_allocated() / 2**30}])
    def check():
        if len({r["sha256"] for r in records}) != 1 or len({r["trainable_parameters"] for r in records}) != 1:
            raise RuntimeError("Trainable parameters diverged between DDP ranks")
        write_json(Path(output) / "rank_parameters.json", records)
    _main_rank_result(accelerator, check)


def _schedule_dataset(args, accelerator, rows):
    block_len = 8 if args.stage == "stage1" else 4
    if accelerator.num_processes > 1 and args.accumulation % block_len:
        raise ValueError(
            f"For per-rank exact {args.stage} ratios, accumulation must be a multiple "
            f"of {block_len}; got {args.accumulation}"
        )
    schedule, report = make_schedule(
        rows,
        args.stage,
        accelerator.num_processes,
        args.accumulation,
        steps=args.steps,
        seed=args.seed,
    )
    return schedule, report


def _main_rank_result(accelerator, function):
    # Broadcast failures too: other ranks must not hang waiting for a failed hash/check.
    payload = [None]
    if accelerator.is_main_process:
        try:
            payload[0] = {"result": function()}
        except Exception as exc:
            payload[0] = {"error": f"{type(exc).__name__}: {exc}"}
    broadcast_object_list(payload)
    if "error" in payload[0]:
        raise ValueError(payload[0]["error"])
    return payload[0]["result"]


def _fresh_output(args, accelerator):
    def create():
        path = Path(args.output)
        if path.exists() and any(path.iterdir()):
            raise ValueError("Use a fresh output directory; --init-adapter is weights-only warm-start")
        path.mkdir(parents=True, exist_ok=True)
        return str(path)
    _main_rank_result(accelerator, create)


def _resume_cache_output(args, accelerator):
    """Open an incomplete cache directory for per-file continuation.

    A completed manifest is rejected so a successful cache can never be
    accidentally overwritten.  Existing shard files are checked by the
    DiffSynth data-process runner and only readable, matching row payloads are
    reused.
    """
    def prepare():
        path = Path(args.output)
        if path.exists() and not path.is_dir():
            raise ValueError(f"Cache output is not a directory: {path}")
        if (path / "manifest.json").is_file():
            raise ValueError("Cache is already complete; use a new output or train from its manifest")
        path.mkdir(parents=True, exist_ok=True)
        return str(path)
    _main_rank_result(accelerator, prepare)


def resolve_warmup_steps(args, updates):
    """Turn a requested ratio into optimizer updates, never microsteps."""
    if updates < 1:
        raise ValueError("optimizer updates must be positive")
    if args.warmup_steps is not None:
        warmup_steps = args.warmup_steps
    else:
        warmup_steps = math.ceil(updates * args.warmup_ratio)
    if not 0 <= warmup_steps <= updates:
        raise ValueError("warmup-steps must lie in [0, optimizer updates]")
    return warmup_steps


def scheduler_factory(args, updates, warmup_steps=None):
    if warmup_steps is None:
        warmup_steps = resolve_warmup_steps(args, updates)
    def factor(step):
        if step < warmup_steps:
            return (step + 1) / warmup_steps
        if args.lr_schedule == "constant":
            return 1.0
        progress = (step - warmup_steps) / max(1, updates - warmup_steps)
        return 0.5 * (1 + math.cos(math.pi * min(progress, 1.0)))
    return lambda optimizer: torch.optim.lr_scheduler.LambdaLR(optimizer, factor)


def validate_training_length_and_saves(args):
    if args.steps is None:
        raise ValueError("Training requires explicit --steps (optimizer updates)")
    if not isinstance(args.steps, int) or args.steps < 1:
        raise ValueError("--steps must be positive")
    if not isinstance(args.save_steps, int) or args.save_steps < 1:
        raise ValueError("--save-steps must be positive")
    if args.save_steps % args.accumulation:
        raise ValueError(
            f"--save-steps={args.save_steps} must be divisible by "
            f"--accumulation={args.accumulation} to save after complete optimizer updates"
        )


def _startup(args, accelerator, phase, state, **details):
    """Expose pre-model work instead of leaving the last log at NCCL startup."""
    entry = {"time_utc": datetime.now(timezone.utc).isoformat(),
             "rank": accelerator.process_index, "phase": phase, "state": state, **details}
    print(json.dumps({"startup": entry}, ensure_ascii=False), flush=True)
    if accelerator.is_main_process and not getattr(args, "plan_only", False):
        with (Path(args.output) / "startup.jsonl").open("a") as stream:
            stream.write(json.dumps(entry, ensure_ascii=False) + "\n")


def _region_preflight(args, accelerator, rows):
    _startup(args, accelerator, "region_preflight", "started",
             mode="prepared_report" if args.prepared_data_report else "full_scan")
    if args.prepared_data_report:
        from samtok_edit21.data.preflight import verify_prepared_region_report
        result = _main_rank_result(accelerator, lambda: verify_prepared_region_report(
            args.prepared_data_report, args.metadata, args.region_cache,
            args.max_pixels, len(rows)))
    else:
        from samtok_edit21.regions.supervision import RegionStore
        store = RegionStore(args.region_cache, args.max_pixels)
        for index, row in enumerate(rows, 1):
            if row["sample_type"] != "edit_ntp":
                store.load(row, args.base_path)
            if index % 1000 == 0 and accelerator.is_main_process:
                _startup(args, accelerator, "region_preflight", "progress",
                         rows_checked=index, rows_total=len(rows))
        result = {"mode": "full_scan", "rows": len(rows)}
    _startup(args, accelerator, "region_preflight", "complete", **result)
    return result


def run_train(args):
    if args.attention_weight:
        from samtok_edit21.training.attention import require_attention_backend
        require_attention_backend()
    validate_training_length_and_saves(args)
    accelerator = _accelerator(args.accumulation)
    args.device = str(accelerator.device)
    if not args.plan_only:
        _fresh_output(args, accelerator)
    set_seed(args.seed)  # same adapter initialization on every rank
    data_preflight = None
    if args.stage == "stage2":
        manifest = json.loads((Path(args.cache) / "manifest.json").read_text())
        args.max_pixels = manifest["identity"]["max_pixels"]
        def validate():
            validate_cache_manifest(manifest)
            assert_models_match(manifest["identity"], args.qwen, args.samtok)
            if args.region_weight or args.attention_weight:
                if not manifest.get("supervision_identity"):
                    raise ValueError("Training requires a conditioning cache built with --region-cache")
        _startup(args, accelerator, "conditioning_cache_validation", "started")
        _main_rank_result(accelerator, validate)
        _distributed_cache_validation(args.cache, manifest, accelerator)
        _startup(args, accelerator, "conditioning_cache_validation", "complete")
        rows = manifest["rows"]
        schedule, report = _schedule_dataset(args, accelerator, rows)
        dataset = ScheduledCache(rows, args.cache, schedule)
        base_identity = manifest["identity"]["models"]
    else:
        _startup(args, accelerator, "metadata_load", "started", metadata=args.metadata)
        rows = read_rows(args.metadata)
        _startup(args, accelerator, "metadata_load", "complete", rows=len(rows))
        if args.region_weight or args.prepared_data_report:
            data_preflight = _region_preflight(args, accelerator, rows)
        schedule, report = _schedule_dataset(args, accelerator, rows)
        dataset = ScheduledMetadata(rows, schedule)
        from samtok_edit21.data.provenance import model_identity
        _startup(args, accelerator, "model_identity", "started")
        base_identity = _main_rank_result(accelerator, lambda: model_identity(args.qwen, args.samtok))
        _startup(args, accelerator, "model_identity", "complete")
    if args.init_adapter:
        init_config = json.loads((Path(args.init_adapter) / "adapter.json").read_text())
        if init_config.get("base_identity") is not None and init_config["base_identity"] != base_identity:
            raise ValueError("Warm-start base model differs from adapter provenance")
        if args.stage == "stage2" and init_config.get("conditioning_identity") != manifest["identity"]:
            raise ValueError("Warm-start Stage 2 conditioning identity differs from cache")
    updates = len(schedule) // (accelerator.num_processes * args.accumulation)
    warmup_steps = resolve_warmup_steps(args, updates)
    factory = scheduler_factory(args, updates, warmup_steps)
    microsteps_per_rank = updates * args.accumulation
    planned_step_checkpoints = math.ceil(microsteps_per_rank / args.save_steps)
    plan = {
        "stage": args.stage,
        "optimizer_updates": updates,
        "world_size": accelerator.num_processes,
        "accumulation": args.accumulation,
        "global_batch": report["global_batch"],
        "effective_warmup_steps": warmup_steps,
        "microsteps_per_rank": microsteps_per_rank,
        "save_steps_microsteps": args.save_steps,
        "planned_step_checkpoints": planned_step_checkpoints,
        "pool_exposure": report["pool_exposure"],
    }
    if accelerator.is_main_process:
        if not args.plan_only:
            write_json(Path(args.output) / "schedule.json", report)
            write_json(Path(args.output) / "run.json", {
                "args": vars(args), "base_identity": base_identity, "optimizer_updates": updates,
                "data_preflight": data_preflight,
                "effective_warmup_steps": warmup_steps,
                "microsteps_per_rank": microsteps_per_rank,
                "planned_step_checkpoints": planned_step_checkpoints,
                "seed_policy": "shared initialization, seed+rank after prepare",
                "init_adapter_semantics": "weights only; fresh optimizer/scheduler",
            })
        print(json.dumps({"training_plan": plan}, ensure_ascii=False), flush=True)
    accelerator.wait_for_everyone()
    if args.plan_only:
        accelerator.end_training()
        return
    from samtok_edit21.training.tracking import TrainingTracker
    _startup(args, accelerator, "wandb_init", "started")
    tracker = TrainingTracker(args, accelerator, plan)  # fail before expensive model loading
    _startup(args, accelerator, "wandb_init", "complete")
    _startup(args, accelerator, "model_load", "started")
    model = SamtokTrainingModule(args, "sft:train")
    _startup(args, accelerator, "model_load", "complete")
    model.tracker = tracker
    logger = ModelLogger(args.output, remove_prefix_in_ckpt="pipe.text_encoder."
                        if args.stage == "stage1" else "pipe.dit.", enable_csv_log=True)
    _startup(args, accelerator, "training", "started")
    launch_training_task(
        accelerator, dataset, model, logger, learning_rate=args.lr,
        weight_decay=args.weight_decay, num_workers=args.num_workers,
        save_steps=args.save_steps, num_epochs=1, max_grad_norm=args.max_grad_norm,
        scheduler_factory=factory, training_seed=args.seed, args=None,
    )
    _startup(args, accelerator, "training", "complete")
    accelerator.wait_for_everyone()
    verify_rank_parameters(model, accelerator, args.output)
    def save():
        config = {"stage": args.stage, "base_identity": base_identity,
                  "supervision": {k: getattr(args, k) for k in ("region_weight", "region_n_min", "attention_weight", "attention_read_weight", "attention_layers", "attention_warmup_steps")}}
        if args.stage == "stage1" and args.region_cache:
            config["supervision_identity"] = model.region_store.identity
        if args.stage == "stage2":
            config["conditioning_identity"] = manifest["identity"]
            config["supervision_identity"] = manifest.get("supervision_identity")
        pipe = accelerator.unwrap_model(model).pipe
        save_adapter(pipe.text_encoder if args.stage == "stage1" else pipe.dit,
                     Path(args.output) / "adapter", config)
    _main_rank_result(accelerator, save)
    tracker.finish()
    accelerator.end_training()


def _distributed_call(accelerator, label, function):
    """Run a local check on every rank and propagate errors without a hang."""
    error, result = None, None
    try:
        result = function()
    except BaseException as exc:  # every rank must still enter gather_object
        error = f"{type(exc).__name__}: {exc}"
    gathered = gather_object([{"rank": accelerator.process_index,
                              "error": error, "result": result}])
    errors = [item for item in gathered if item.get("error")]
    if errors:
        details = "; ".join(f"rank {item['rank']}: {item['error']}" for item in errors)
        raise RuntimeError(f"{label} failed: {details}")
    return gathered


def _validate_cache_inputs(payload, row, *, supervision_identity=None):
    if payload.get("row_hash") != row_hash(row):
        raise ValueError("Cache payload row hash disagrees with metadata")
    inputs = payload.get("inputs")
    if not isinstance(inputs, dict):
        raise ValueError("Cache payload is missing inputs")
    if "prompt_embeds_mask" not in inputs:
        raise ValueError("Missing text attention mask")
    sources = row["edit_image"]
    source_count = 1 if isinstance(sources, str) else len(sources)
    if len(inputs["edit_latents"]) != source_count:
        raise ValueError("Source latent count differs from metadata image count")
    validate_conditioning(inputs)
    supervision = inputs.get("region_supervision")
    if supervision_identity is not None or supervision is not None:
        from samtok_edit21.regions.supervision import validate_supervision
        validate_supervision(supervision, inputs, row, require_positions=True)
        if supervision["identity"] != supervision_identity:
            raise ValueError("Conditioning cache supervision identity mismatch")


def _cache_manifest_shard(args, accelerator, rows):
    """Validate and index one rank's payloads in parallel with other ranks."""
    output = Path(args.output)
    rank = accelerator.process_index
    rank_dir = output / str(rank)
    if not rank_dir.is_dir():
        raise ValueError(f"Missing cache rank directory: {rank_dir}")
    supervision_identity = None
    if args.region_cache:
        from samtok_edit21.regions.supervision import RegionStore
        supervision_identity = RegionStore(args.region_cache, args.max_pixels).identity
    entries, seen = [], set()
    for path in sorted(rank_dir.glob("*.pth"), key=lambda p: int(p.stem)):
        if not path.stem.isdigit():
            raise ValueError(f"Cache payload name is not numeric: {path}")
        payload = torch.load(path, map_location="cpu", weights_only=True)
        index = payload.get("row_index")
        if not isinstance(index, int) or index in seen or not 0 <= index < len(rows):
            raise ValueError("Duplicate/out-of-range cache row")
        seen.add(index)
        row = rows[index]
        if payload.get("identity") != args.conditioning_identity:
            raise ValueError("Cache payload identity disagrees with conditioning identity")
        _validate_cache_inputs(payload, row, supervision_identity=supervision_identity)
        digest = row_hash(row)
        checksum = file_hash(path)
        side = {"row_index": index, "row_hash": digest,
                "sha256": checksum, "identity": args.conditioning_identity}
        side_path = path.with_suffix(".json")
        reusable_side = False
        if side_path.is_file():
            try:
                reusable_side = json.loads(side_path.read_text()) == side
            except (OSError, ValueError, TypeError):
                reusable_side = False
        if not reusable_side:
            write_json(side_path, side)
        entries.append({"row_index": index,
                        "row_hash": digest,
                        "sha256": checksum,
                        "cache_file": str(path.relative_to(output))})
    shard_dir = output / "manifest_shards"
    shard_dir.mkdir(parents=True, exist_ok=True)
    summary = {"format": FORMAT, "rank": rank,
               "world_size": accelerator.num_processes,
               "identity": args.conditioning_identity,
               "row_count": len(entries), "entries": entries}
    write_json(shard_dir / f"rank-{rank:02d}.json", summary)
    # The full entry list stays on the shared filesystem.  Returning it through
    # gather_object would replicate hundreds of megabytes on every rank.
    return {"rank": rank, "row_count": len(entries)}


def _merge_cache_manifest(args, accelerator, rows):
    if not accelerator.is_main_process:
        return
    output = Path(args.output)
    shard_dir = output / "manifest_shards"
    entries, seen_indices, seen_paths = {}, set(), set()
    for rank in range(accelerator.num_processes):
        path = shard_dir / f"rank-{rank:02d}.json"
        summary = json.loads(path.read_text())
        if (summary.get("format") != FORMAT or summary.get("rank") != rank
                or summary.get("world_size") != accelerator.num_processes
                or summary.get("identity") != args.conditioning_identity):
            raise ValueError(f"Invalid cache manifest shard: {path}")
        for entry in summary.get("entries", []):
            index, relative = entry.get("row_index"), entry.get("cache_file")
            if (not isinstance(index, int) or not 0 <= index < len(rows)
                    or index in seen_indices or not isinstance(relative, str)
                    or relative in seen_paths):
                raise ValueError("Duplicate/out-of-range cache manifest entry")
            if entry.get("row_hash") != row_hash(rows[index]):
                raise ValueError("Cache manifest shard row hash mismatch")
            resolved = Path(output / relative).resolve()
            try:
                canonical = resolved.relative_to(output.resolve()).as_posix()
            except ValueError as exc:
                raise ValueError("Cache manifest path escapes output") from exc
            if canonical != relative:
                raise ValueError("Cache manifest path is not canonical")
            expected_rank = Path(canonical).parts[0] if Path(canonical).parts else None
            if expected_rank != str(rank):
                raise ValueError("Cache manifest shard rank/path mismatch")
            seen_indices.add(index)
            seen_paths.add(relative)
            entries[index] = {**rows[index], "_cache_file": relative}
    if seen_indices != set(range(len(rows))):
        raise ValueError("Cache does not cover every metadata row exactly once")
    manifest = {"format": FORMAT, "identity": args.conditioning_identity,
                "row_count": len(rows),
                "rows": [entries[index] for index in range(len(rows))]}
    if args.region_cache:
        from samtok_edit21.regions.supervision import RegionStore
        manifest["supervision_identity"] = RegionStore(args.region_cache, args.max_pixels).identity
    validate_cache_manifest(manifest)
    write_json(output / "manifest.json", manifest)  # atomic publication after distributed validation


def _distributed_cache_validation(cache, manifest, accelerator):
    """Validate cache payloads concurrently, then check global row coverage."""
    gathered = _distributed_call(
        accelerator, "conditioning cache validation",
        lambda: {"indices": verify_cache_shard(
            cache, manifest, accelerator.process_index, accelerator.num_processes)}
    )
    all_indices = []
    for item in gathered:
        result = item.get("result") or {}
        all_indices.extend(result.get("indices", []))
    expected = set(range(len(manifest["rows"])))
    if len(all_indices) != len(expected) or set(all_indices) != expected:
        raise RuntimeError("Distributed cache validation did not cover every row exactly once")


def run_cache(args):
    if args.cache_save_retries < 0:
        raise ValueError("cache-save-retries must be nonnegative")
    if args.cache_save_retry_backoff < 0 or not math.isfinite(args.cache_save_retry_backoff):
        raise ValueError("cache-save-retry-backoff must be finite and nonnegative")
    accelerator = _accelerator()
    args.device = str(accelerator.device)
    if args.resume_cache:
        _resume_cache_output(args, accelerator)
    else:
        _fresh_output(args, accelerator)
    set_seed(args.seed)
    rows = read_rows(args.metadata)
    if any(row["sample_type"] == "edit_ntp" for row in rows):
        raise ValueError("Cache only accepts FM metadata, never edit_ntp")
    args.conditioning_identity = _main_rank_result(
        accelerator, lambda: conditioning_identity(args.qwen, args.samtok, args.te_adapter,
                                                   args.max_pixels, args.metadata))
    te_config = json.loads((Path(args.te_adapter) / "adapter.json").read_text())
    if te_config.get("base_identity") is not None and te_config["base_identity"] != args.conditioning_identity["models"]:
        raise ValueError("TE adapter base model differs from cache provenance")
    if te_config["stage"] != "stage1":
        raise ValueError("--te-adapter must be a Stage 1 adapter")
    dataset = ScheduledMetadata(rows, list(range(len(rows))), cache=True)
    model = SamtokTrainingModule(args, "sft:data_process")
    launch_data_process_task(accelerator, dataset, model, ModelLogger(args.output),
                             num_workers=args.num_workers, args=None,
                             resume=args.resume_cache,
                             save_retries=args.cache_save_retries,
                             save_retry_backoff=args.cache_save_retry_backoff)
    accelerator.wait_for_everyone()
    _distributed_call(accelerator, "cache manifest shard", lambda: _cache_manifest_shard(args, accelerator, rows))
    accelerator.wait_for_everyone()
    _main_rank_result(accelerator, lambda: _merge_cache_manifest(args, accelerator, rows))
    accelerator.end_training()

def _parser():
    parser = argparse.ArgumentParser(description="SAMTok with DiffSynth runners")
    sub = parser.add_subparsers(dest="command", required=True)
    for command in ("cache", "train"):
        p = sub.add_parser(command)
        p.add_argument("--qwen", default=DEFAULT_QWEN)
        p.add_argument("--samtok", default=DEFAULT_SAMTOK)
        p.add_argument("--output", required=True)
        p.add_argument("--base-path", default=".")
        p.add_argument("--max-pixels", type=int, default=1048576)
        p.add_argument("--num-workers", type=int, default=0)
        p.add_argument("--device", default="cuda")
        p.add_argument("--metadata")
        p.add_argument("--cache")
        p.add_argument("--te-adapter")
        p.add_argument("--resume-cache", action="store_true",
                       help="Resume an incomplete cache, reusing readable row payloads")
        p.add_argument("--cache-save-retries", type=int, default=8,
                       help="Retries for transient shared-filesystem cache writes")
        p.add_argument("--cache-save-retry-backoff", type=float, default=2.0,
                       help="Initial seconds for exponential cache-write backoff")
        p.add_argument("--stage", choices=("stage1", "stage2"), default="stage2")
        p.add_argument("--steps", type=int)
        p.add_argument("--accumulation", type=int)
        p.add_argument("--rank", type=int)
        p.add_argument("--dropout", type=float)
        p.add_argument("--lr", type=float)
        p.add_argument("--weight-decay", type=float)
        p.add_argument("--ntp-weight", type=float, default=0.05)
        p.add_argument("--fm-weight", type=float, default=1.0)
        p.add_argument("--max-grad-norm", type=float, default=1.0)
        p.add_argument("--seed", type=int, default=20260920)
        p.add_argument("--save-steps", "--save-every", type=int, default=2000,
                       help="Checkpoint interval in per-rank microsteps; must divide accumulation")
        p.add_argument("--lr-schedule", choices=("constant", "cosine"),
                       help="Stage 1 defaults to cosine; Stage 2 defaults to constant")
        warmup = p.add_mutually_exclusive_group()
        warmup.add_argument("--warmup-ratio", type=float,
                            help="Fraction of optimizer updates; defaults to 0.04/0.025 for Stage 1/2")
        warmup.add_argument("--warmup-steps", type=int,
                            help="Explicit optimizer updates, overriding the stage default ratio")
        p.add_argument("--init-adapter")
        p.add_argument("--region-cache", help="Independent frozen region cache (Stage 1 and conditioning cache builder)")
        p.add_argument("--prepared-data-report", help="Stage 1: reuse offline metadata_report.json instead of scanning all image/coverage assets")
        p.add_argument("--region-weight", type=float, default=0.0, help="C coefficient; suggested 0.5, zero disables")
        p.add_argument("--region-n-min", type=float, default=16.0)
        p.add_argument("--attention-weight", type=float, default=0.0, help="Calibrated final A coefficient; Stage 2 only")
        p.add_argument("--attention-read-weight", type=float, default=0.5)
        p.add_argument("--attention-layers", type=int, nargs="+", default=[7, 11, 15, 19, 23], help="Zero-based DiT layers")
        p.add_argument("--attention-warmup-steps", type=int, default=500, help="Successful optimizer updates, independent of LR warmup")
        if command == "train":
            p.add_argument("--wandb-mode", choices=("disabled", "offline", "online"), default="disabled")
            p.add_argument("--wandb-project", default="samtok-edit")
            p.add_argument("--wandb-entity", default="2200012743-peking-university")
            p.add_argument("--wandb-name")
            p.add_argument("--wandb-id")
            p.add_argument("--plan-only", action="store_true",
                           help="Validate provenance and print exposure plan without loading models or writing output")
    return parser


def normalize_args(args):
    if hasattr(args, 'resume_adapter') and not hasattr(args, 'init_adapter'):
        args.init_adapter = args.resume_adapter
    if not hasattr(args, 'save_steps'):
        args.save_steps = getattr(args, 'save_every', 2000)
    # Fill missing fields for the legacy Python wrappers, using the same parser
    # defaults as the public CLI instead of maintaining another recipe.
    parser_defaults = _parser().parse_args([getattr(args, "command", "train"),
                                           "--output", args.output])
    for key, value in vars(parser_defaults).items():
        if not hasattr(args, key):
            setattr(args, key, value)
    if getattr(args, 'init_adapter', None):
        config = json.loads((Path(args.init_adapter) / 'adapter.json').read_text())
        if config['stage'] != args.stage:
            raise ValueError('--init-adapter belongs to another stage')
        for key in ('rank', 'dropout'):
            if getattr(args, key, None) is not None and getattr(args, key) != config[key]:
                raise ValueError(f'Explicit --{key} conflicts with warm-start adapter')
            setattr(args, key, config[key])
    defaults = {
        "stage1": {"accumulation": 8, "rank": 64, "dropout": 0.05, "lr": 4e-5, "weight_decay": 0.05},
        "stage2": {"accumulation": 4, "rank": 32, "dropout": 0.0, "lr": 1e-4, "weight_decay": 0.01},
    }[args.stage]
    if args.lr_schedule is None:
        args.lr_schedule = "cosine" if args.stage == "stage1" else "constant"
    if args.lr_schedule not in {"constant", "cosine"}:
        raise ValueError("lr-schedule must be constant or cosine")
    if args.warmup_steps is not None and args.warmup_ratio is not None:
        raise ValueError("Choose either warmup-steps or warmup-ratio")
    if args.warmup_ratio is None and args.warmup_steps is None:
        args.warmup_ratio = 0.04 if args.stage == "stage1" else 0.025
    if args.warmup_ratio is not None and (not math.isfinite(args.warmup_ratio) or not 0 <= args.warmup_ratio <= 1):
        raise ValueError("warmup-ratio must be finite and lie in [0, 1]")
    if args.warmup_steps is not None and args.warmup_steps < 0:
        raise ValueError("warmup-steps must be nonnegative")
    for key, value in defaults.items():
        if getattr(args, key) is None:
            setattr(args, key, value)
    if args.accumulation < 1 or (args.steps is not None and args.steps < 1):
        raise ValueError("accumulation/steps must be positive")
    for key in ("ntp_weight", "fm_weight", "region_weight", "attention_weight", "attention_read_weight"):
        if not math.isfinite(getattr(args, key)) or getattr(args, key) < 0:
            raise ValueError(f"{key} must be finite and nonnegative")
    if not math.isfinite(args.region_n_min) or args.region_n_min <= 0 or args.attention_warmup_steps < 0:
        raise ValueError("Invalid region n_min / attention warmup")
    if not args.attention_layers or len(set(args.attention_layers)) != len(args.attention_layers) or any(i < 0 or i >= 32 for i in args.attention_layers):
        raise ValueError("Attention layers must be unique indices in [0,31]")
    args.attention_layers = sorted(args.attention_layers)
    if args.stage == "stage1" and args.attention_weight:
        raise ValueError("Attention supervision is Stage 2 only")
    if args.prepared_data_report and (args.command != "train" or args.stage != "stage1" or not args.region_cache):
        raise ValueError("--prepared-data-report requires Stage 1 train and --region-cache")
    if args.command == "train" and args.stage == "stage1" and args.region_weight and not args.region_cache:
        raise ValueError("Stage 1 C requires --region-cache")
    if args.command == "train" and args.stage == "stage2" and args.region_cache:
        raise ValueError("Stage 2 reads regions from conditioning cache; use --region-cache during cache construction")
    return args


def main(argv=None):
    args = normalize_args(_parser().parse_args(argv))
    if args.command == "cache":
        if not args.metadata or not args.te_adapter:
            raise SystemExit("cache requires --metadata and --te-adapter")
        run_cache(args)
    else:
        if args.stage == "stage1" and not args.metadata:
            raise SystemExit("stage1 train requires --metadata")
        if args.stage == "stage2" and not args.cache:
            raise SystemExit("stage2 train requires --cache")
        try:
            validate_training_length_and_saves(args)
        except ValueError as exc:
            raise SystemExit(str(exc)) from exc
        run_train(args)


if __name__ == "__main__":
    main()
